---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
---
version: "3.9"
services:  
  a-train:
    hostname: "a-train"
    container_name: "a-train"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/m-rots/a-train:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - "${APPFOLDER}/a-train/data:/data:rw"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
