---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  plex-update-tool:
    hostname: 'plex-update-tool'
    container_name: 'plex-update-tool'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'TMDB_API_KEY=${TMDBAPI}'
      - 'RUN_EVERY_N_HOURS=${RUN_EVERY_N_HOURS}'
    image: 'mynttt/updatetool'
    restart: '${RESTARTAPP}'
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - '${APPFOLDER}/plex-update-tool:/config:rw'
      - '${APPFOLDER}/plex/database/Library/Application Support/Plex Media Server:/plexdata'
    labels:
      - 'dockupdater.enable=true'
networks:
  proxy:
    driver: bridge
    external: true
