---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  rsnapshot:
    hostname: "rsnapshot"
    container_name: "rsnapshot"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "lscr.io/linuxserver/rsnapshot"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - "${APPFOLDER}/rsnapshot:/config:rw"
      - "unionfs/snapshots:/data"
      - "/etc/locatime:/etc/localtime:ro"
    labels:
      - "dockupdater.enable=true"
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
