---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:latest'
    restart: "${RESTARTAPP}"
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --pilot.dashboard=false
      - --log.level=ERROR
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.endpoint=${DOCKERSOCKET}
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.${DOMAIN}`)
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --providers.docker.swarmMode=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.2
      - --entryPoints.traefik.address=:8080
      - --entrypoints.https.http.middlewares=chain-authelia@file
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN}
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.dns-cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.keyType=EC384
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=60
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - '${SECURITYOPS}:${SECURITYOPSSET}'
    volumes:
      - '${APPFOLDER}/traefik/rules:/rules'
      - '${APPFOLDER}/traefik/certs:/tmp/certs'
      - '${SOCKET}:${SOCKET}:ro'
      - '${APPFOLDER}/traefik/acme/acme.json:/acme.json'
      - '${APPFOLDER}/traefik/traefik.log:/traefik.log'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}'
      - 'CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}'
    labels:
      - 'dockupdater.enable=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.http-catchall.entrypoints=http'
      - 'traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.traefik-rtr.entrypoints=https'
      - 'traefik.http.routers.traefik-rtr.priority=10'
      - 'traefik.http.routers.traefik-rtr.rule=HostHeader(`traefik.${DOMAIN}`)'
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
      - 'traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file'
networks:
  proxy:
    external: true
  docker_socket:
    external: true
