---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
## Mullvad Config example
services:
  gluetun:
    hostname: "gluetun"
    container_name: "gluetun"
    image: "qmcgaw/gluetun:latest"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: "${RESTARTAPP}"
    extra_hosts:
      - "analytics.plex.tv:127.0.0.1"
      - "metrics.plex.tv:127.0.0.1"
      - "metric.plex.tv:127.0.0.1"
      - "mf.svc.nhl.com:127.0.0.1"
      - "mlb-ws-mf.media.mlb.com:127.0.0.1"
      - "playback.svcs.mlb.com:127.0.0.1"
    networks:
      - ${DOCKERNETWORK}
    environment:
      - "PUID=${ID}"
      - "PGID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "VPN_SERVICE_PROVIDER=mullvad"
      - "VPN_TYPE=wireguard"
      - "WIREGUARD_PRIVATE_KEY=xxxxxPRIVATEKEYxxxxxx"
      - "WIREGUARD_ADDRESSES=10.64.89.118/32"
      - "SERVER_CITIES=Frankfurt"
      - "OWNED_ONLY=yes"
      - "HTTPPROXY=on"
      - "HTTPPROXY_LISTENING_ADDRESS=:8888"
    volumes:
      - "${APPFOLDER}/gluetun/:/gluetun:rw"
networks:
  proxy:
    driver: bridge
    external: true
