---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  cloudflared:
    hostname: "cloudflared"
    container_name: "cloudflared"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "cloudflare/cloudflared:latest"
    command: "tunnel --no-autoupdate --config=/home/nonroot/.cloudflared/config.yaml run"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/cloudflared:/home/nonroot/.cloudflared:rw"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
