---
version: ""3.9""
services:
  <APP>:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
