---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  jellyfin:
    devices:
      - /dev/dri:/dev/dri

  plex:
    devices:
      - /dev/dri:/dev/dri

  emby:
    devices:
      - /dev/dri:/dev/dri
