---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  jellyfin:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
