---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  nabarr:
    hostname: "nabarr"
    container_name: "nabarr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=022"
    image: "cloudb0x/nabarr:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/nabarr:/config:rw"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
