---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  dashmachine:
    hostname: "dash"
    container_name: "dash"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "ghcr.io/dockserver/docker-dash:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}:${APPFOLDER}"
      - "unionfs:/mnt"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.dash-rtr.entrypoints=https"
      - "traefik.http.routers.dash-rtr.rule=Host(`dash.${DOMAIN}`)"
      - "traefik.http.routers.dash-rtr.tls=true"
      - "traefik.http.routers.dash-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.dash-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.dash-rtr.service=dash-svc"
      - "traefik.http.services.dash-svc.loadbalancer.server.port=3001"

networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
