  dashmachine:
    hostname: "dash"
    container_name: "dash"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "DASHDOT_OS_WIDGET_ENABLE=true"
      - "DASHDOT_CPU_WIDGET_ENABLE=true"
      - "DASHDOT_CPU_DATAPOINTS=20"
      - "DASHDOT_CPU_POLL_INTERVAL=1000"
      - "DASHDOT_RAM_WIDGET_ENABLE=true"
      - "DASHDOT_RAM_POLL_INTERVAL=1000"
      - "DASHDOT_STORAGE_WIDGET_ENABLE=true"
    image: "ghcr.io/dockserver/docker-dash:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.dash-rtr.entrypoints=https"
      - "traefik.http.routers.dash-rtr.rule=Host(`dash.${DOMAIN}`)"
      - "traefik.http.routers.dash-rtr.tls=true"
      - "traefik.http.routers.dash-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.dash-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.dash-rtr.service=dashmachine-svc"
      - "traefik.http.services.dash-svc.loadbalancer.server.port=3001"
networks:
  proxy:
    driver: bridge
    external: true
