name: Get Changes

on:
  schedule:
    - cron: '0 */1 * * * '
  workflow_dispatch:

permissions: read-all

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0
        clean: false

    - name: Run command to generate Mds
      run: |
        echo "Run command"
        if test -f "./.github/run.sh"; then
           bash "./.github/run.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}
